version: '3'
services:

    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: jurnals
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
            DB_HOST: db
            DB_DATABASE: books
            DB_USERNAME: root
            DB_PASSWORD: ""
        working_dir: /var/www
        volumes:
            - ./:/var/www:delegated
            - /var/www/vendor
            - ./storage:/var/www/storage
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - laravel

    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
        volumes:
            - ./:/var/www:delegated
            - ./storage:/var/www/storage
            - ./nginx/conf.d:/etc/nginx/conf.d
        networks:
            - laravel

    db:
        image: mysql:5.7
        container_name: db
        restart: unless-stopped
        tty: true
        ports:
            - "3307:3306"
        environment:
            MYSQL_DATABASE: books
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - laravel

volumes:
    dbdata:
        driver: local

networks:
    laravel:
        driver: bridge
